source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!
use_frameworks!

target 'MQTTClientmacOS' do
    platform :osx, '10.12'

	pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClientmacOSTests' do
    end
end

target 'MQTTClientiOS' do
    platform :ios, '8.2'

    pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClientiOSTests' do
    end
end

target 'MQTTClienttvOS' do
    platform :tvos, '10.1'

    pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClienttvOSTests' do
    end
end
